#!/bin/bash
export RABBIT_MQ_CONNECTION_STRING="amqp://default_user_IlR2D-NZ6d5U0tWa34m:9ZH8eHWc3bmpCxrbboHArn3qiUP1VieK@localhost:5672/"
export RABBIT_MQ_QUEUE_NAME="shortener"
export MONGODB_COLLECTION_NAME="documents"
export MONGODB_CONNECTION_STRING="mongodb://admin:admin@localhost:27017"
export MONGODB_DATABASE_NAME="documents"
IMAGE_TAG="gosumer-rabbitmq"
docker run -d --name my-go-app-container \
  -e RABBIT_MQ_CONNECTION_STRING=$RABBIT_MQ_CONNECTION_STRING \
  -e RABBIT_MQ_QUEUE_NAME=$RABBIT_MQ_QUEUE_NAME \
  -e MONGODB_COLLECTION_NAME=$MONGODB_COLLECTION_NAME \
  -e MONGODB_CONNECTION_STRING=$MONGODB_CONNECTION_STRING \
  -e MONGODB_DATABASE_NAME=$MONGODB_DATABASE_NAME \
  -p 8080:8080 $IMAGE_TAG
