apiVersion: apps/v1
kind: Deployment
metadata:
  name: gosumer-rabbitmq
  labels:
    app: gosumer-rabbitmq
  namespace: short
spec:
  selector:
    matchLabels:
      app: gosumer-rabbitmq
  template:
    metadata:
      labels:
        app: gosumer-rabbitmq
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: gosumer-rabbitmq
        image: registry.gitlab.edge.com.py/edge-codes/gosumer-rabbitmq:latest
        ports:
        - containerPort: 8080
        env:
        - name: RABBIT_MQ_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: rabbitmq-default-user
              key: connection_string
        - name: RABBIT_MQ_QUEUE_NAME
          value: "shortener"
        - name: MONGODB_COLLECTION_NAME
          value: "codes"
        - name: MONGODB_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: MONGO_CONNECTION_STRING
        - name: MONGODB_DATABASE_NAME
          value: "short-codes"
        resources:
            requests:
                memory: "64Mi"
                cpu: "250m"
            limits:
                memory: "1Gi"
                cpu: "1000m"
      imagePullSecrets:
        - name: edge-registry
