
apiVersion: v1
kind: Service
metadata:
  name: gosumer-rabbitmq
  labels:
    app: gosumer-rabbitmq
  namespace: short
spec:
  selector:
    app: gosumer-rabbitmq
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP
